### ISSUE TITLE
SegFault From libsoup

### ISSUE THREAD

**Issue by lots0logs** [bcedu/VGrive#54]
I think this one can be avoided by using a single soup session instance instead of creating a new instance for each request. :thinking: 

```
LOG: INFO: Security Audit.gdsheet not changed

Thread 5 "Sync thread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff08e2700 (LWP 62356)]
0x00007ffff7ca3b7d in g_atomic_ref_count_compare () from /usr/lib/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff7ca3b7d in g_atomic_ref_count_compare () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff7cd3a6d in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff7cbee09 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7264feb in  () at /usr/lib/libsoup-2.4.so.1
#4  0x00007ffff7cd2492 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff7cd36f8 in g_hash_table_remove_all () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff7cd373f in g_hash_table_destroy () at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff7265ca6 in  () at /usr/lib/libsoup-2.4.so.1
#8  0x00007ffff7dad491 in g_object_unref () at /usr/lib/libgobject-2.0.so.0
#9  0x000055555556892b in app_vgrive_client_make_request ()
#10 0x000055555556e579 in app_vgrive_client_get_file_info_extra ()
#11 0x00005555555744b5 in app_vgrive_client_check_remote_files ()
#12 0x0000555555573d61 in app_vgrive_client_check_remote_files ()
#13 0x0000555555576a2f in app_vgrive_client_sync_files ()
#14 0x0000555555576ae5 in _app_vgrive_client_sync_files_gthread_func ()
#15 0x00007ffff7c9dc11 in  () at /usr/lib/libglib-2.0.so.0
#16 0x00007ffff6dbd4cf in start_thread () at /usr/lib/libpthread.so.0
#17 0x00007ffff716c2d3 in clone () at /usr/lib/libc.so.6
```

**Comment by bcedu** [comment]
Closed with de29f95bd11ca8b80c93d0421fc29493573f4fa1
